name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  windows:
    name: Windows
    runs-on: windows-2019

    env:
      LUA_VERSIONS: '5.4.2 5.3.6 5.2.4 5.1.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare environment
        run: bash ./.ci/install-env-windows

      - name: Build and test cffi
        run: bash ./.ci/build-cffi-windows

      - name: Upload dll file
        uses: actions/upload-artifact@v4
        with:
          name: cffi-lua
          path: build-5.4.2/cffi.dll
